---
title: "Average fish across years"
author: "Lia Domke"
date: "3/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Read in data
```{r}
fish17 <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A8dba01ba-ebec-4b45-afe5-391947abcc6e"), stringsAsFactors = FALSE, header = TRUE)

fish18 <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A0cae20e4-8f8e-427e-b7b9-5d8dd7111ec0"), stringsAsFactors = FALSE, header = TRUE)

fish19 <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A347cd81e-15a2-41f9-a73b-e344615548bf"), stringsAsFactors = FALSE, header = TRUE)

fish20 <- read.csv("Data/fish_beach_seine_2020_RAW_unchecked.csv", stringsAsFactors = FALSE, header = TRUE)

fish21 <- read.csv("../APECS_DM/Data/fish_mass_2021_derived.csv", stringsAsFactors = FALSE, header = TRUE)
```

Libraries
```{r}
library(dplyr)
library(tidyr)
library(lubridate)
```

join together consistent data
```{r}
fish <- fish17 %>%
  full_join(fish18) %>%
  full_join(fish19)

names(fish)
names(fish20)

fish20 <- fish20 %>%
  select(c(sp_code, date, start_time, end_time, slope, tide_height, tide_time, species_common, 
           species_scientific, taxon, fork_length, unmeasured, unmeasured_sm, bay_code, bay_sample)) %>%
  unite(unmeasured, c(unmeasured, unmeasured_sm), na.rm = TRUE, remove = TRUE) # Combine uneamsured columns

fish <- fish %>%
  select(c(sp_code, date, start_time, end_time, slope, tide_height, tide_time, species_common, 
           species_scientific, taxon, fork_length, bay_code, bay_sample))

# add in abundance for both
fish20$abundance <- as.numeric(ifelse(is.na(fish20$fork_length), paste(fish20$unmeasured), 1))
fish$abundance <- as.numeric("1")

# combine all data
fish_all <- fish %>%
  full_join(fish20) %>%
  select(-unmeasured) %>%
  unite(bayID, bay_code:bay_sample)
```

Unique species caught ever
```{r}
unique(fish_all$sp_code)
```


Average number of fish caught at a single site

```{r}
total <- fish_all %>%
  filter(taxon == "Vertebrata" | taxon == "vertebrate") %>%
  group_by(species_common, species_scientific, bayID) %>%
  summarise(total = sum(abundance))

avg <- total %>%
  group_by(species_common, species_scientific) %>%
  summarise(avg = mean(total))
```

Want the all unique species caught, at how many sites, and what sites
```{r}
# add in fish21 

fish.all <- fish21 %>%
  mutate(bayID = bay_ID) %>%
  dplyr::select(c(sp_code, date, start_time, end_time, slope, tide_height, tide_time, species_common, 
                  species_scientific, taxon, fork_length, bayID, abundance)) %>%
  full_join(fish_all) %>%
  filter(taxon == "vertebrate" | taxon == "Vertebrata")


species_occ_bysite <- fish.all %>%
  mutate(year = year(as.Date(date))) %>%
  group_by(sp_code) %>%
  count(bayID)

test <- fish.all %>%
  mutate(year = year(as.Date(date))) %>%
  group_by(bayID) %>%
  count(sp_code)

test2 <- test %>%
  dplyr::select(-n) %>%
  pivot_wider(names_from = "bayID", values_from = "sp_code")


site.wide <- pivot_wider(species_occ_bysite, names_from = "bayID", values_from = "n", values_fill=0)
#write.csv(site.wide, "Data/species_by_site.csv")


species_occ_bysite %>%
  group_by(sp_code) %>%
  dplyr::summarise(site_n = sum(n)) %>%
  left_join(site.wide)

site_occ <- read.csv("Data/site_occ_by_species.csv", stringsAsFactors = FALSE, header = TRUE)

library(unpivotr)


site_occ <- site_occ[-1,]
names(site_occ)
colnames(site_occ)[XOTZ] <- "NATZ_A" # no finding xotz

na.omit(site_occ)

site_occ %>%
  tidyr::unite("united", BAKE_A:KLWH_A, "_", na.rm = TRUE)
```
